# Generated by Django 6.0.1 on 2026-02-18 09:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0003_notification'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Notification',
        ),
    ]
