# Generated by Django 6.0.1 on 2026-03-13 07:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0009_alter_order_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orderitem',
            name='product_image',
            field=models.ImageField(blank=True, null=True, upload_to='order_items/snapshots/'),
        ),
        migrations.AlterField(
            model_name='orderitem',
            name='variant_name',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
