# Generated by Django 6.0.1 on 2026-02-05 04:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0005_remove_product_category_product_created_at_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='NestedCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('subcategory', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='nested_categories', to='product.subcategory')),
            ],
        ),
        migrations.AddField(
            model_name='product',
            name='nested_category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='product.nestedcategory'),
        ),
    ]
