# Generated by Django 6.0.1 on 2026-02-05 09:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0006_nestedcategory_product_nested_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='description',
            field=models.TextField(default='No description available'),
            preserve_default=False,
        ),
    ]
