# Generated by Django 6.0.1 on 2026-02-07 05:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0009_product_category_alter_product_stock'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='carousel',
            options={'ordering': ['order'], 'verbose_name_plural': '2. Home Carousels'},
        ),
        migrations.AlterModelOptions(
            name='offerbanner',
            options={'verbose_name_plural': '1. Offer Banners'},
        ),
    ]
