# Generated by Django 6.0.1 on 2026-03-06 08:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0012_review'),
    ]

    operations = [
        migrations.AddField(
            model_name='offerbanner',
            name='title_color',
            field=models.CharField(default='#FFD700', help_text='Choose hex color (e.g. #FFD700)', max_length=7),
        ),
    ]
