# Generated by Django 6.0.1 on 2026-03-06 08:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0013_offerbanner_title_color'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='offerbanner',
            name='title_color',
        ),
    ]
