# Generated by Django 6.0.1 on 2026-03-14 04:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0016_material_alter_carousel_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='offer_end_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
