# Generated by Django 6.0.1 on 2026-02-27 07:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0013_address_landmark'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Notification',
        ),
    ]
